### ISSUE TITLE
嵌入块中，子级有序列表样式

### ISSUE THREAD

**Issue by winter60** [royc01/notion-dark#10]
![image](https://user-images.githubusercontent.com/23653326/172530927-a690a91a-bcc0-4780-ae68-19ad583a126c.png)

**Comment by royc01** [comment]
这就神奇了。。。我这边显示正常
![1](https://user-images.githubusercontent.com/38906705/172543783-c32c6aea-ac47-428c-9443-9465fe111240.jpg)

**Comment by winter60** [comment]
![image](https://user-images.githubusercontent.com/23653326/172544847-8d5904b5-2c56-4674-b532-08b2287c628b.png)
我这里有个这个样式，你那里有吗？好像不是这个原因，我也不知道，我在群里面问问大家吧。
