### ISSUE TITLE
日记快捷键“Alt+5”优化建议

### ISSUE THREAD

**Issue by J-o-T-e-r** [royc01/notion-dark#11]
开发者你好！个人使用“notion-dark”主题后发现，通过日记快捷键“Alt+5”打开的是前一次关闭的“daily note”，而不是像siyuan自带的那样唤起一个选择框。请问可否考虑优化一下？

**Comment by royc01** [comment]
这个和默认主题的逻辑是一样的，已经用过快捷键再按的话就会打开前次的日记文档
