### ISSUE TITLE
ctrl+shift+f 搜索面板 内容区域面包屑似乎不显示？

### ISSUE THREAD

**Issue by winter60** [royc01/notion-dark#12]
![image](https://user-images.githubusercontent.com/23653326/175485284-c5ac9d3e-d3b5-4637-bb2a-5d111e893d3b.png)

**Comment by royc01** [comment]
我这边面包屑是正常的喔

**Comment by winter60** [comment]
> 我这边面包屑是正常的喔

抱歉，下次提issue会仔细检查~  是我的custom.css的原因，还在检查是哪个样式 【尴尬】

**Comment by winter60** [comment]
再次抱歉，发现好像是siyuan的bug，只要在内容界面按F5刷新就会消失。算了，也不影响我就不去社区提了，最近删除了qq，不登录社区了~ 打扰了，rc大佬
