### ISSUE TITLE
在ctrl+shift+f搜索面板动态输入内容时，以及ctrl+p全局搜索中使用alt+单击 某条内容时，顶部栏样式异常 

### ISSUE THREAD

**Issue by winter60** [royc01/notion-dark#14]
![image](https://user-images.githubusercontent.com/23653326/177183059-2cae4c1f-7fe0-44d9-89d6-4b86ffbf9df2.png)
顶部栏被截取了一部分

**Comment by winter60** [comment]
你试试呢？是不是我总引入了dark+js的原因哦

**Comment by royc01** [comment]
是bug，下个版本修复
