### ISSUE TITLE
Transparency error in the bottom menu

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-dark#15]
1) Friend, I've been using your theme for a few months now. I had never noticed, but I think the bottom panel was transparent. Correct? It is now a solid color capping the information. Look at her hiding the "blockquote" information in the image below! Could you make this bar transparent?

![image](https://user-images.githubusercontent.com/90691302/181918582-debb8357-c996-49b6-9356-88b7c284ed34.png)

2) In the side panel there is an error spacing between the icons.
![image](https://user-images.githubusercontent.com/90691302/181919447-fdc1aaad-43fa-4fce-a887-56231d07c26e.png)

**Comment by royc01** [comment]
i can't fix NO.1

**Comment by taozina0587** [comment]
Your new update is perfect! Thank you very much! Can I make a suggestion? If you ever have time, could you create a theme called "Notion-Black"? I think it would be beautiful! Look how I customize mine with black colors...

![image](https://user-images.githubusercontent.com/90691302/182818559-d39b39a6-0114-435b-93d9-2127b3660719.png)
