### ISSUE TITLE
Callout - Image quality error in the list.

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-dark#16]
I use Linux Mint and study using a list (outline method). The callout implementation is perfect! But when used in lists, it has an image error. Could you please try to fix it? Callout is an amazing tool to help with studies.

![image](https://user-images.githubusercontent.com/90691302/183247273-26e30a0b-cb48-4474-8bcc-31d38e8433e5.png)

SiYuan: 2.1.5
System: Linux Mint

**Comment by royc01** [comment]
thanks, it will be fixed in next version
