### ISSUE TITLE
Callout: List image error.

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-dark#17]
Friend, the error still persists in the icon in the callout when it is in the list. I noticed that in the v2.3.2 theme update there is a fix for the problem. The error still persists in Siyuan on Linux Mint. If you fixed it on windows or mac, could you help me fix it on linux?

![image](https://user-images.githubusercontent.com/90691302/183270288-a010db98-e693-4734-b334-b343bb4a3bf7.png)

**Comment by royc01** [comment]
![222](https://user-images.githubusercontent.com/38906705/183270489-799f4e59-f200-42fa-9cef-fe6605cfc59b.jpg)

**Comment by taozina0587** [comment]
朋友，思源更新主题到v2.3.2，但错误依旧。 我从 GIthub 下载了主题，然后它就消失了！ 我不明白，但它的工作！ 非常感谢。

**Comment by taozina0587** [comment]
你能帮我翻译菜单上的标注吗？ 我一个中文都听不懂。 我在用谷歌翻译。

**Comment by royc01** [comment]
ctrl+shift+i   clear your cache and run window.location.reload()

**Comment by taozina0587** [comment]
Can you help me translate the callouts on the menu? I can't understand any Chinese.

**Comment by royc01** [comment]
[notion-theme.zip](https://github.com/royc01/notion-dark/files/9275986/notion-theme.zip)

**Comment by royc01** [comment]
overwrite the `theme.js` file
