### ISSUE TITLE
钉住后标题栏无法正常显示内容

### ISSUE THREAD

**Issue by bobo0810** [royc01/notion-dark#18]
@royc01 非常感谢您的工作，目前有个小疑问请教下：钉住后标题栏无法正常显示内容，将造成不便~
![image](https://user-images.githubusercontent.com/26057879/185556830-13cfc24d-424b-4cc2-bfeb-da29a64d756b.png)

**Comment by bobo0810** [comment]
@royc01

**Comment by royc01** [comment]
你好，这个逻辑跟浏览器的逻辑是一致的，建议添加emoji以区分文档，暂时不改了，感谢反馈。

**Comment by bobo0810** [comment]
> 你好，这个逻辑跟浏览器的逻辑是一致的，建议添加emoji以区分文档，暂时不改了，感谢反馈。

一些疑问：
1. 官方 之前也存在这个问题，后来更新后显示完整的标题内容。
2. 我的理解是 钉住代表最常用、经常点击的文档，而非收纳起来。

**Comment by royc01** [comment]
> > 你好，这个逻辑跟浏览器的逻辑是一致的，建议添加emoji以区分文档，暂时不改了，感谢反馈。
> 
> 一些疑问：
> 
> 1. 官方 之前也存在这个问题，后来更新后显示完整的标题内容。
> 2. 我的理解是 钉住代表最常用、经常点击的文档，而非收纳起来。

我理解你的意思，可能我经常用emoji吧，钉住的文档就不用在意什么标题，恰恰因为是最常用的，标题图标也烂熟于心，而剩下的空间都是留出给其他文档标题，我是出于以上的考虑，或者我看看后面怎么再优化一下。

**Comment by bobo0810** [comment]
> > > 你好，这个逻辑跟浏览器的逻辑是一致的，建议添加emoji以区分文档，暂时不改了，感谢反馈。
> > 
> > 
> > 一些疑问：
> > 
> > 1. 官方 之前也存在这个问题，后来更新后显示完整的标题内容。
> > 2. 我的理解是 钉住代表最常用、经常点击的文档，而非收纳起来。
> 
> 我理解你的意思，可能我经常用emoji吧，钉住的文档就不用在意什么标题，恰恰因为是最常用的，标题图标也烂熟于心，而剩下的空间都是留出给其他文档标题，我是出于以上的考虑，或者我看看后面怎么再优化一下。

感谢。因为钉住的文档并非一成不变，也会经常变换的。
- 比如最近的多个项目在忙，我会钉住几个文档。等下周可能就是其他几个文档需要钉住。
