### ISSUE TITLE
Custom emoji size in "doc tree" is wrong

### ISSUE THREAD

**Issue by eslam-gomaa** [royc01/notion-dark#2]
Custom emoji size in "doc tree" is wrong

![image](https://user-images.githubusercontent.com/33789516/145688611-4dc5e830-9b7c-4a96-a9e9-410ef7176859.png)

**This happens with all custom emojis**

![image](https://user-images.githubusercontent.com/33789516/145688627-d509def4-78d9-4e1c-ac33-e280871f8466.png)

---

The issue does NOT exist on the light theme

![image](https://user-images.githubusercontent.com/33789516/145688718-d14e1d7d-841e-4d93-bdec-84e3b86506ca.png)

**Comment by royc01** [comment]
This bug has been fixed in version 1.2.6, Thanks
