### ISSUE TITLE
建议将dark主题默认的第二个自定义字体色彩修改为灰色

### ISSUE THREAD

**Issue by jimmyyukio** [royc01/notion-dark#22]
因为在白天的主题中设置为浅灰色的字体相较于一般色彩的字体更不明显，而在夜晚模式主题下，设置成灰色的字体与普通字体区别不大，所以作此建议
![图片](https://user-images.githubusercontent.com/60495173/195736552-eccfa67a-5eba-4a26-b9d8-5435b23a25ea.png)
最新版本 notion theme 的字体显示
![图片](https://user-images.githubusercontent.com/60495173/195737080-f2657cae-2705-43da-99e2-747dd55f1504.png)
 notion dark 主题自定义修改色彩后
![图片](https://user-images.githubusercontent.com/60495173/195737249-11d74cc9-5434-44ec-9f60-e8cf07a7c6a8.png)
我认为，这样的显示效果才更符合色彩的用意

**Comment by royc01** [comment]
感谢反馈，下个版本调整

**Comment by jimmyyukio** [comment]
好的，谢谢！
