### ISSUE TITLE
Table head -- `font color` is the same as `background color`

### ISSUE THREAD

**Issue by eslam-gomaa** [royc01/notion-dark#3]
Table head `font color` is the same as `background color`

![image](https://user-images.githubusercontent.com/33789516/146957918-7542d22b-0fb0-4cbe-bbdd-1a814120dff8.png)

**Comment by royc01** [comment]
fixed

**Comment by eslam-gomaa** [comment]
@royc01 
I Updated the theme from Bazar & still not fixed

**Comment by royc01** [comment]
![8](https://user-images.githubusercontent.com/38906705/147397277-e244a5dc-17d5-4384-a27d-c07bc9d0fd06.png)
It seems to be working, plz download again
