### ISSUE TITLE
Option to disable  toolbar on hover

### ISSUE THREAD

**Issue by Clouder0** [royc01/notion-dark#4]
Credit for your theme. After a recent update, the toolbar on the top only shows on hover(notion-dark theme). The idea is novel and may be worth trying, yet I found myself more accustomed to the traditional style.

For example, when I want to change Light/Dark mode, I've to move my pointer to the arrow, wait for the toolbar to expand, and then find the icon and click. The animation takes some extra time and is sometimes confusing.

![Peek 2021-12-22 21-12](https://user-images.githubusercontent.com/41664195/147098239-9f353d70-fcfb-4206-a204-2d6cd39849a6.gif)

I'd appreciate it if you are nice enough to add an option to disable this feature.

**Comment by royc01** [comment]
This feature is disabled
