### ISSUE TITLE
可以优化下PDF样式吗？

### ISSUE THREAD

**Issue by winter60** [royc01/notion-dark#5]
非常感谢rc大佬的主题，现在才发现这款主题，配色简直惊艳到我了~是我见过最好看的思源暗黑主题！（平时用的护眼的Tsundoku Green）

喜欢在思源阅读PDF，但看到notion-dark的PDF配色样式有些瑕疵。主要是PDF的背景色和前景色，选中文本的前景色和背景色，以及七种高亮的前景色和背景色。大佬有时间的话，可以优化一下么~（求求了😁）

![image](https://user-images.githubusercontent.com/23653326/164983428-ec45b756-de33-47c0-a17f-6f3857ea217c.png)

**Comment by winter60** [comment]
在开发者工具下调了下，好像可以
![image](https://user-images.githubusercontent.com/23653326/165468456-6cd83397-b7f8-4416-a2cd-81e94053b8e4.png)

**Comment by royc01** [comment]
这个还在优化中，过几天更新吧

**Comment by royc01** [comment]
可以告诉一下怎么改掉字体的么

**Comment by winter60** [comment]
> 可以告诉一下怎么改掉字体的么

他是有两层，一层是canvas ，一层是真正的字体（用的透明的）。
1. 把canvas隐藏掉
2. 去掉混合模式
3. 修改真正的字体。
![image](https://user-images.githubusercontent.com/23653326/165664978-fb434cd5-36b5-4c6f-b457-8d083c2e91bd.png)
@royc01 
![image](https://user-images.githubusercontent.com/23653326/165665337-67766180-1734-4276-805a-273aadaf92f3.png)

好像是这样

**Comment by winter60** [comment]
我也不确定这样修改对不对，仅供参考，大佬你看着来~

**Comment by royc01** [comment]
我也是这样，就是不知道有没有什么隐患。。。我继续鼓捣下

**Comment by royc01** [comment]
不玩了，图片显示有问题，后续还是等官方优化吧，改个背景色算了
