### ISSUE TITLE
列表转导图异常

### ISSUE THREAD

**Issue by Li-Juan-Siwei** [royc01/notion-dark#7]
![image](https://user-images.githubusercontent.com/93273663/166710568-0a4c2c24-af90-4cfb-9e86-b11655ab232d.png)
这是导图
![image](https://user-images.githubusercontent.com/93273663/166710706-64c9f006-64ec-4731-96e2-3b47a0a2e6ce.png)
这是l列表,
显然:存在两个问题
第一.列表块中如果有代码块,转为导图后显示会异常.
第二,如果列表块中换行(shift+enter换行,而不是enter换行)后输入代码块, 代码块会跟在列表块的后面,而不是平齐.造成导图排列变的很长

**Comment by royc01** [comment]
修了一波，先试试
