### ISSUE TITLE
Changes to the animation effect

### ISSUE THREAD

**Issue by taozina0587** [royc01/notion-dark#8]
Thank you so much for the effort to create the theme. It turned out amazing! I would like to edit some things for personal use. One of the changes is the animation speed when working with list (outline method).
Could you help me control this option? I'm looking in the "theme.css" file, but I can't find it! I am very inexperienced in this matter!

![image](https://user-images.githubusercontent.com/90691302/167293975-fcfc9364-f027-448d-bd3b-6e0600b0113a.png)

In the image, I highlight the icons that animate when hovering the mouse.

**Comment by royc01** [comment]
protyle-gutters
