### ISSUE TITLE
横版斜杠菜单建议可以 键盘左右选择

### ISSUE THREAD

**Issue by loudawang** [royc01/notion-dark#9]
最新的主题有了横版斜杠菜单，很赞。
目前只能键盘上下键选取，建议增加 键盘 左右 键

**Comment by royc01** [comment]
主题只是改了样式，但是操作还是以官方操作为准，暂时改不了。。。

**Comment by loudawang** [comment]
好嘞，不着急




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 上午9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [royc01/notion-dark] 横版斜杠菜单建议可以 键盘左右选择 (Issue #9)





 
主题只是改了样式，但是操作还是以官方操作为准，暂时改不了。。。
